### ISSUE TITLE
Temporary online interpreter 

### ISSUE THREAD

**Issue by lyxal** [SjoerdPennings/BRASCA#1]
[I wrapped the file into a kind of online interpreter using Try it Online](https://tio.run/##zVv7U@O2Fv49f4UKbUlKAmEfXTaX0MJ2e0tblh1gpp1hqK8SK4m2tuVaMtnM7e2/vvcc@RG/EsvLkxmGYEvn@85DR0eP@As1E97zfT/4xF1fBIrIhewSl6pZaxIIlyjuMpK8chjzo8cB9Wz4E7/A/@B3ylrxAxXQMRvR8Z@t1tihUpLjgMoxfYOfBy0CPxsbGxcKGnRJwKZcKhZIAlLIDQ04HTlMQgPd0GYTYlnc48qy2pI5k86gpV/gz6aWoTumYtKX2HhH6gZDcnWdf07hWT//aJR7tMQ4ChiZMwCgNvemhN2wAKyGH6kk4xkFXRH3uyJwAE0sV9gM5P5IHckyvN9zn9k97hGbKpo@5hPiCe0C6A5gO1xSpRbtziBtkpEPDSzsDuKXPZBlu3M1GPT2rnOdJiIgVpdYBECZF7osoIq1C6IKQBVg6C8ZOgpB82@uELJbelrkkffMDvV95tltEdjtSHCnkzZnYLM6zSFKllb9iWIQxc4ZMeYRH5ygmE0WTBX8Qx001cJKWpR9dDnjksy54xCpBMQAhU9qxsgIHP4nU8QXkisuvELEzWfcYZYjhC9B6H//l5PIyBgDAgMWRfkCwYO8AGxhxW/KUTqOAirRe/N9KGcE/DmCxkpoqdqy6eDxoYEVNdDu7mLrjKPLzsD3Wek31AkZEZNlsCNSBQq@jzHw41oQ9Lhu1FmtyEgoBVkGkNeqZUXt6rTjnmSBavejJvUKGjHAHnn81ZovCZSVFz7RibUAIfwk5xVzRCo2P0ICpsLAywRNeRDFTTLEECYadgU2tSYQflb5B6DZTyx2ASMQCSV5P@UkmbKSh7FLkn/z/JKnZAjDiW5UZBqaZLmlgSKuxd6jqt6jcu9MzGW5b8k4BCsHMOapu9IoNwQjHTvVevebqlsWPepUG6Ufu/Acp1LJKlXWb4pBlcFJWnRSWTpaUJTDvKmaVQds9K4oNw41eNleQmSGZujAXKml6eROMLkTB@xB2sWU30mhRiF37OhhEU8x18/XJDg7J/MJpBDhujhFlKdqzP6FSRqck7RH31xtlOdwxEs8k6DkfaN9nBVzXSEGzBLgxK/F5YfEqhnwSve5hk4Jbn2XpCX20t1b8IPl4MUCItAlNJiCTTwFlaSvy1eckaG63PEXZEIOJiDJoy47LL8dkwM04GGrdSnAslhngqtG4bRLQojDib07RqMDCrUxfia74x1sKh0xJ7aYe0SEyg9V3FzujqUm1uJYoyKoZWnrWZZLoUaxYiNGDECdTBkcGy8ml87qG58@bcRzexx/5BgDKYpsjDuX@tme2TBLQpacArpurf@PgjaDlFYXBzrmM2@yQRos8iGQhkdW1FWF2OtifMZtciVxXG@Vo6z0YJPohHkAI@EwX3isGQb9ivjNWC1bFPXLYVwaDnvm4vYMxD0zF/fMQNxzc3HPDcS9MBf3wkDcS3NxLw3EfWsu7lsDca/Mxb0yELdvLm7fQNxrc3GvDcQ5DcLYZFj82kCeSeSxBuPCxLlvGwwMk4FmNxgZJu79oUEsm4yNWYNwMYnmn5rEi0nA/NJIYFLs52YDPRlEUwlMwLCIqkXd@s/WWtT8Vs1lELJ6RbYMFNHL4Zq5cnvvurNOUG663h6SvQqLnFIsd30sE0Vm/2sl9@2NAdk8su1KXLqc36tLPE3OqFHZp6NtahAkPeR3EY5wF1E9AsmeCclvkORp6CjuO4tHIPmNCcldJHkCsTOF6LH5DZdVFfj9k93dNWH7lTapsENHPALHr0wo/oEU3370hQcLkMfwupHbpR5AfwW3YVgGx0OBnQmsKuKPEgDatNOpStLHXM05rJEaZKV/kPS7s8s75fyPibm@1vnw3Q@P4M@vTfj9jfzOzh@B3t8m9Cyk9/uj8PsD@FVE30XlCrFEnCJxX2/GieUG19HaUiG7uQgCDMwzqkQ5NkcZmaAcaZRk39ZMmfzGopk2x9U4xw1wjPTpIk68ybdixZ9DSHYDawUPULAd@g4f6009UEVM1iB8buaht2lZYv2vPOvlnrwp8WSb3pRV0p7eQYeSNi5q44qbvPlxfERCKiGjHfLPckbCTYsw4Hea8isYWm/Qx7tq9fya2tyYn19jP@Lpc3tZHReuCD1lYkjclPZwE1qf7bf73ahrp3rl08hHd@On9zV@ekJ2WB8Lt4yH73SyjK5kxCeo/d7es1emcZfe32jvPdvvGAB@kc5py8OW2iSdm7mjR/FxjAnklwgp59TXjlVzQbhiriTCu3XyvvcMPzLQ71z7UKhkUlKzgLGH1XF874YY38ZklYcDJTteoB3HwsN50kuNCeESCZYPHyfcU22pUKVt/KNXTLVqTItqrA6A@DQRYba2dj4I7mk4r7NMXOlGF55rrk5yY0xrkDwyqS5zPhT3HtRmsCbGQfIG5uCxOaDMUwSEcI4pPs517V7VZmtOqW6cknMnqjm9VqsFVKLOh0PyYj@@pYb/HwzJy1er@@V2GAHiSjPBU03dHUjX632S1Xt5OSayQHv7wfTu59V@/dlaA@VWvdofdbnLQUhg15foa@OuJPv3rGyTQrpqEi@vOU92zwwUE3oprw@R8fbg0cWbk5P4qk2dlstz1NLVtZVnqQUVynfeKje78Uc3aY9n6VStrdvpQhjZw60tAzufrVTVxOiPr23q7CZKe3ml4xH7dB2cdW4DNd@tVvOpOrfCsUuFK8bzG@GpQDjkR0fM6w1ygAb5lUkJdRu97x12NN8BHTRZSexVS2Impm56V@IQbfFvcI@@R/kw5jh8uuYY6iODv0II6wcwxHD4dC3xPVrikgUux4q2dTejG6@@s49cmUz9m0gABrat75dRh3wIXb8mQ2lzY83Tr7VH@ay2ltEHZPQzsMCSbQ4ViWxyGJyl2DNA@zlFw@9mNIPr5eG2DeCuEO43vHzW0zfXost8680dbd98gZcj11amuRKzt3dd46FVWqVKZS8g1l5pW3VjMqctzC33pevhvaraK9wx2DyJbtLqt37A9ApRpt@Hwe9cxPcxyldKq2/@4WAuK7B5iZdwuYLaYULmM@bBmkMAcKCjVXGwFcBOYDlh19z@a3bhI/reR4nNGULrQ0y90cVVyzxJlm6BxOQKC4eCnU/1jm7yHZHid0OMEg37OGa@Ir@wxUjA8Maj/yAIfVW4r13OmXHHt/oPJEd0a0G5zQvhsui7NXPmKTIPhDft4kaVmIOrCCCJPN2o8tp4e35@dj4gVd0LR0FRh/TbYzuQFF2qLCBX3CPMqBDdeT1x8XAEo0eXpa2mdebKk6TP3Bihw5Xz9XK1QVcU3Z/@Dw)

Just linking it here for now

**Comment by SjoerdPennings** [comment]
Thanks!

**Comment by SjoerdPennings** [comment]
[Updated for v0.3](https://tio.run/##zVt7c9s2Ev9fnwK1rrVYS7aUR5PoLLd2ml7d1nHG9sx1xuPyIBGSmJIES4BWNH189dwu@BBfEkG/NeOxRAC7v31gsQCW/lLOuff8tR98tl2fB5KIpegSl8p5axpwl0jbZSRpchjzo8cB9Sz4FzfgL/ibsVb8QAZ0wsZ08nurNXGoEOQooGJC3@L3YYvAZ2tr61xChy4J2MwWkgWCABVyTQObjh0moIPqaLEpMU3bs6VpdgRzpsawpRrw01Y01MCUTNqInXeF6jAil1f55xSe9fOPxrlHKx6HASMLBgyoZXszwq5ZAFrDr1SQyZyCrMj32yLjALqYLrcY0P2BOoJlcH@wfWb1bI9YVNL0sT0lHlcmgOHAbNcWVMplxximXTL0oYOJw4H8agSi7BiXw2FvcJUbNOUBMbvEJMCUeaHLAipZp0CqwKiCGdpLhI5EpvmWS2TZLT0t4shbZpf6PvOsDg@sTkTYMNLuDHRWJzl4yUqrP1J0otg4Y8Y84oMRJLPIksmCfaiDqlqaSY@yjS7mtiAL23GIkBx8gMI3OWdkDAb/nUnic2FLm3sFj1vMbYeZDue@AKJ//p2jyMgEHQIdFkn5HJkHeQLYw4xbyl46iRwqkbv9IRRzAvYcQ2fJFVWl2XTy@NDBjDooc3exd8bQZWNge5b6NXVCRvh05ezIqYILtsc88OtGJmhx1clYL8iYSwlRBjhvFMuM@tVJZ3uCBbLTj7rUC6iFAEfk@a@XfAWgLDz3iQqsBRbcT2JeMUakZPMzJGAyDLyM05QnUdwlAwzZRNOugKZWBdzPCv8AMPuJxs5hBiKgJO6nmASTZvIwNknyM48veUpGMJ3oVkWkoUmUWykowlocPa4aPS6PzvhcFvu2iF2wcgJjnLoriXJTMJLRqJa731TcMumxUa2UfmzCM1xKBasUWbUUnSrDJ@lhpLSUtyAph3kzOa922KitSDd2NWjsrFhkpmbowFqpqKngTjC4Ewf0QTrFkG@krMah7VjRwyI/yVw/n5Pg6pysJxBCuOviElFeqjH6FxZpME7SH21zuVVew5FfYpmES942ysZZMlcVZEAtAS78ilx@SqxbAS/VmCsYlPCtH5L0xFFqeAs@mA6eL8EDXUKDGejEk5BJ@ip9xRUZsstdf0mmZH8KlDzqsoNy64TsowIPWq0LDprFPBNMNQ5nXRKCH06tvQkqHbhQC/1nujfZxa7C4Qti8YVHeCj9UMbdxd5EKGAtG3NUZGqaSnum6VLIUcxYiRECECeTBsfKi8Glq/rW589xehx5HzlCN4r8Gr3OpX52XNbJEoclJ8Bb9Va/I5fN8Elzi33l8ZmWrIsGy7wDpM6RJXVZQfaq6J1xn1xCHGdbZR8rPWgTFS73YR4c5NOODZOgX@G9Ga1lU6J@2YlLk2GgT26gQe6ZPrlnGuSe65N7rkHuhT65FxrkXuqTe6lB7ht9ct9okHulT@6VBrnX@uRea5B7o0/ujQY5p4Eb60yLXxrQ0/E81mBe6Bj3XYOJoTPRrAYzQ8e83zfwZZ25MW/gLjre/GMTf9FxmJ8bEdSh@Kc@xeQR5i09nTD9981o7wyMVnkVU4tYtARC2gBbv1r@2//b3sg/f8B0EYSsXqRtDZHUJr5mjd8ZXBmbCOXSjJ0RGVRo5IRiku5jcsszp3Zrse9sDUn70LIq@dJVXlKdmCpwWp0qrLtDNdylh/jOwzGefcpHANnTAfk1gjwJHWn7zvIRQH6tA3IPQR6D78zAeyz72hZV@4b7B7u3p4P2S6VSboUOfwSMX@pA/A0hvvvkcw@2TY9hdS2zCzWB/ghug7DMHK8ydqewG4q/CmDQoYZRFaSPbLmwYWfXICr9g6Dfn17cKeZ/dNT1lYqH779/BHt@pYPvL8R3evYI8P7SgWcivF8fBd9vgK/C@84rd7Yl4BSB@@oIka@O5Q43pgrZI1EgoKGecSWXI30uYx0uh4pLctqsJ0z@OFRPmqNqPkcN@GjJ00U@8dHkmpOKHIfkDLOW8BAJW6Hv2BN1FAmi8OkGDjeNPPQ2PUuo/51HvbpJ0AWeXC7ookr60zsYUJLGRWlcfp1XP86PiEgly@hc/0bGSLApEhr4TlJ8BUWra4X4NLAeX1Oda@Pza/RHPFVtIKr9wuWhJ3UUiUfpHh6dq4qETr8bDTWqdz6NbHQ3dvpQY6cnpIfNvnBLf/hWBcuokCS@9@33Bs9e6fpdWnXSgX1mcQtuaAD4Il3jVldGtUG7YtsfXyrpsPwXshQL6itDywUntmSuINy7dTC/94g/1pDvTNmUy2SRkvOAsYeVcXLvipjcRmWVlxwlPZ6jHifcw3XTS5UJ7hIRFg/vJzjHhESRdvAf1Zphs6IY6x0gvhNFNtvbux@57Sl2nrEKZOnBF97Org96EwxzEEwyoS9zzxWPHtZGtCbKQfAa6rBjdUDaJwkQsW0M@XHs6/SqDo1zQnXjEJ27F87JtV4sgBINPhiRF6/jWjv8vT8iL1@tH5c7cQQWlwoJ3s2q4QC6Xu7jrNyrEp9IA52dB5O7nxf7zY2lBsiterE/qfTXBiKBVZ@yb/S7Eu1fs7R1EuuqRb28Bz3eO9UQjKutvboKxxrIw/O3x8dxwVCdlKv74FIB3to74YII5cq9ysNv/Kgunck8f0JvdMGNrNH2toaeT9eKqqP0x5c2NXYTob280PGMfboGzhq3gZjv14v5VI1bYdiVwBXz@S33ZMAd8oPDF/UK2UeF/MKEgLyN3veJO6pvnw6b7CwG1ZSYjqqb1nwcoC7@A@ZR1aAPo46Dp6uOkbpC@CMEt34ARYxGT1cT36EmLljg2pjRtu5mdmMBP/tkS52lv40AYGJbqkqOOuRj6Po1EUqpG3Oefq0@yne3tYg@IqKfAAWmbAvISESTy@H8xXw9t59SbviGSTN2vTy7HQ12l8juv1hE11MVeFFJ4mZ1R8c5X2CJ58bMNJdi9gZXNRZaJ1UqVLaMsrY0b13dZ05aWFvuS9aDexW1V6g5aB9H9cCq1Q@Y2iGK9K0efHMkrs8oF8ZWVzDiZC4L0L7AUmJbQu4wJYs582DPwYFxoLxV2qArYDuF7YRVU8XYrAAkenulhOYUWatLTXXQZcuWfpAsVYXE4Aobh/aJOtNN3m0pvtOiFVrYpwnzJfmZLcccJjRe/gdB6MtCnXk5SsYD36l/EA7RkAVx2ufcZdE7QQvmSbIIuDfr4tEUX4BxCHDiebhRrrX17uzs9GxIqoYXLoOiAelbb7sQBl0qTQBXPBXMiBBV6x67eD2C/qIS0VbTzHLtXdINj0LoaO0Kvdpf0DVp9uf/Aw)

**Comment by SjoerdPennings** [comment]
[Updated for v0.5.1](https://tio.run/##zVt7c9s2Ev9fnwK1r5VUS7acR5P4LLd2kl7d1nHGdud643FZSIQkpiTBkKBlTx9fPbcLPkSQkAjGT8@0sUlg97dPLIBlcC1m3H/6Mgg/OV7AQ0Gi66hHPCpmrUnIPSIcj5HslctYkDwOqW/DP@kL/Av@m7JW@kCEdMxGdPxHqzV2aRSRg5BGY/oaf99pEfhZW1s7FTCgR0I2dSLBwogAFXJJQ4eOXBbBADnQZhNiWY7vCMvqRMyddHda8gX@rEsacmJOJn@JgzcjOWBIzi/U5xSeDdRHI@XRgsd@yMicAQNqO/6UsEsWgtbwVxqR8YyCrMj32zLjEIZYHrcZ0P2euhEr4H7vBMzuOz6xqaD5Y2dCfC5NANOB2aYTUSGuO92dfEiBPgywcDqQX8xAlJ3u@c5Of/tCmTThIbF6xCLAlPmxx0IqWKdEqsRIwwztFcWuQKbqm3Nk2as8LeNQLbNJg4D5doeHdich3O3mwxnorE5y8JKFVn@g6ESpcUaM@SQAIwhmk2smSvahLqrq2spGVG10NnMiMndcl0SCgw9Q@E3MGBmBwf9gggQ8coTD/ZLHzWeOyyyX8yACon/@rVBkZIwOgQ6LpAKOzEOVAI6w0jdVLx0nDlWUWz6HyHOdMUQJ2DYXRj9C8EAVd/19HM0ITBwBR8ElNGmePAIDGGAlA6TP9HB0wVuqFsX3ReqX1I0Z4ZNFxCAnDRd8n/LAX1cyQbeRg7rLBRlxISBVAeeVYlnJuDrpHD9ioegMkiH1AhohwBkq/@WSLwBUhQe7yuxcYsGDLHGWE01OVg2zkIk49AueV43EdEgBGLJJYreEplYFPCgKfw8wB5nGTiGMEVC2eOSYIias7GFqkuxPFV/2lAwhJumaJl3RLFUuFJRgLc8e6WaPqrMLPlfE3o5SF9QGMCa725JICcFExq5e7kFTcaukR129UgapCU9wPY6YVmT5puxUBT7ZiG5OS3oLknKZPxUzvcMm78p0U1eDl50Fi0Joxi4suJKaXCEIrhDEBX2QTnnd6OasRrHj2snDMj/BvEAtbPCJBXWHUnOoL2FhdNnHmAumWAeLg2w5g@TDPQ9XqGqlgItPqUYAs1ZI75FBtZCojOoPybYySvpIFedwObWSrGVgmSDobudryaqrzEsn6slnbpgpplsFW2Rw0YgBeEeIRZRkpGaGZdXEuZxzAZMyRPVTspE4S05fLUN7rVbTZ2HM6m07JE9Wc/q9sTmKwyogTOnjxHryqTe1cA9yeg0ZyyM0nEIk@AK2L4HcM2EZCFuazeCaTMjuBFTuU4/tVd@OyS6GzV6rdcYhnnBzA6E9iqc9EkPemthbYww14EJtzDeTrfEmDo1cPic2n/uExyKIRTo82hpHEpiD@yLkaVlSYsvyKNTFVmrCBAAYorD1Sp0sxZZXkmufPqVbsiRZkQPMOkkaxCTl0aA4r5iTsvxGjoC3HC3/TjJcgU9ez@7KBFl4U8xo4bVqm9ygRVLnGrIX5chPxyibsKXeVXmwTuTqugvJb0@tUlckmIEmdgpaK1bQg2qwVxx425zctgG5J@bknhiQe2pO7qkBuWfm5J4ZkHtuTu65AblvzMl9Y0DuhTm5FwbkXpqTe2lA7pU5uVcG5NwGbmwSFj83oGfieaxBXJgY922DwDAJNLtBZJiY900DXzaJjVkDdzHx5h@a@IuJw/zUiKAJxT/Xdsj6GzYOGRYEpsSzR1jq9U0y9t/I5tC/AZsNEzYhspHL3Yk8wdXxoYsVWF@qSjAmg3Cj4eDGQh4Xd0Y9QgGl3kJLJHS6reqCLQVIVnsokGY0rBW8/Xt7pWOo57faqteofC5LIY@3asqZje2L7ipCSkW1gduoqkaOKG5fA9y88cKh@FLsG@gH@7Z9xw6gc9kNauCnfcR3Go/wakE8AMi@CcivEeRR7AoncK8fAOTXJiC3ksQi2BS8x3YunUi3lbx7sFtbJmi/lCrlduzyB8D4pQnE3xDi26uA@8sS9R1b3cjskQygj@FNEFaZ403h5gQ2fumvETDo0G5Xl6QPHDF3YA/bICv9g6DfHZ/dKuZ/TNT1lcyH7948gD2/MsH3F@I7PnkAeH@ZwLMQ3q8Pgu83wKfxvlPtJr4CnCLwQB6u88WB9f7KUqF4WQAEDNQz0nI5MOcyMuGyL7lk9zBmwqgXBWbSHOj5HDTgYyRPD/mkh/ZLDmUUDtnpfi3hHSRsx3g/Kg/pQRQ@WcHhczMPvcnICup/q6gXd2ymwLNrN1NU2Xh6CxMq0ngojccvVfVjfCREtCyTG6/PMkaGTZIwwHeU4yspWl64pQef9fia6twYX1CjP@LLZp5I7xcej31huoPzFzu4QS@ZumIPZ2yj27HT@xo7PSI9rPaFG/rDtzJZJn1aaUfEoL/95IWp3@VNXR3YZ5bPFboGAL7I17jFZWpt0tacZaTXrSYs/4UsozkNpKHFnBNHMC8i3L9xMr/zjD8ykO9E2pSLbJESs5Cx@5VxfOeKGN9EZdr7nIoeT1GPY@7juunnygR3SQhH9@8nGGORQJE28B9qFGHTshjLHSDtFkA27fbmB@74kp3fXSSy/OAL@xaWJ70xpjlIJoXUV7jSS2fXn@g1UQ6CN1CHk6oDyj5BgIjjYMpPc1@nrzsfV4TqpSla6XtQ5FouFkBJJu8NybOXaSsr/r07JM9fLJ@nnDgCi3OJBK/r5XQAXS/3YVHuRfNbooHOxr3JPVDFfvXZUgPkVr3YV7L8dYBIaNeX7Cv9rkL71yJtk8LaZFGvcImRyy9@/1RL0jctQ2SnThLNzU7SIRnYJnnmlxTndCnOYk65SnLKVSWntOrcQG1num0xNWcCh1vHBo7G5VGLbMLAlu/909eHh2lrY53XLVoRKv3GS9sRSqJUG5W1lxH4I4d0xjP1Gqjbg7C2h@22gaWPl4pqEgQPL20efE2E9lWh0wz6eA1cNG4DMd8tF/OxGldj2IXAmnh@zX0Rcpd87/J5vUJ2USE/syiCOpre9Q0Iqm@XNkpc23pKzETVTduN9lAX/wHzyL71@1HH3uNVx1Be6XyMwa3vQRHD4aPVRPt/bdDEARNzxvzHsLVEfWF1Ocb/PV4H@g4d6IyFnoMbs9btJEX8zItdOcKktlxHAJAPbdn/S13yIfaCmsQutY56HdTqo9qCUIvoAyL6EVBgNTeHwjpq0uOg9s/Uc/sx54bfITZj11fZbRiwO0d2/8W2177sma02W1fVndS8X2DRu3KDpeyU@tsXNRZaJlUuVLFBvLaZVivtRUlaWJLvSta9OxXVxJNer@7qKX14Z9YpdGZIM/lUT9JsqTuX5MMUKUUQMnkgE@XfqOJ3kGk7VLVNXt8bre@MXz/Db1ocAaXhhMxnzIctPgfGoYwq4YBNge0Edu92TX90s34r9duVHM0xspY9BPJc2REt82ReacJKwZU6FdaP5BVK9qVm@QtNoxTIrsYsEOQndj3ikHiw1yYM40CUPniqZvN04lv5D6RtNGRJnPVT7rHkC9c58wWZh9yf9vAkmM/BOAQ4cRVuUkqvvT05OT7ZIbrppbvXZEL@DfcmpGuPCgvAlQ/hCyIk3wEcpo6bfrPQarpxWIxVQgB8TLPDWHnPe4OjSjpcWYVoMGLo6zFWN6u0bs@2hLg@QBe0aZWsllyqzyq5FWI3Frle3OaiLhUTfz79Hw)
